name: Firmware

on:
  pull_request:
    paths:
      - firmware/**
      - .github/workflows/firmware.yml
  push:
    branches:
      - main
    paths:
      - firmware/**
      - .github/workflows/firmware.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        working-directory: firmware
        run: pio run
